import { useEffect, useId, useRef, useState, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes } from 'react';

type Tone = 'primary' | 'secondary' | 'danger' | 'tertiary';
export function Button({ tone = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { tone?: Tone }) { return <button className={`v-button v-button--${tone} ${className}`} {...props} />; }
export function Link({ className = '', ...props }: React.AnchorHTMLAttributes<HTMLAnchorElement>) { return <a className={`v-link ${className}`} {...props} />; }

export function Field({ label, hint, error, required, children }: { label: string; hint?: string; error?: string; required?: boolean; children: (props: { id: string; 'aria-describedby'?: string; 'aria-invalid'?: boolean }) => ReactNode }) {
  const id = useId(); const descriptionId = hint || error ? `${id}-description` : undefined;
  return <div className="v-field"><label htmlFor={id}>{label}{required && <span aria-hidden="true"> *</span>}</label>{children({ id, 'aria-describedby': descriptionId, 'aria-invalid': Boolean(error) || undefined })}{(hint || error) && <span id={descriptionId} className={error ? 'v-field__error' : 'v-field__hint'}>{error || hint}</span>}</div>;
}
export function TextInput(props: InputHTMLAttributes<HTMLInputElement>) { return <input className="v-input" {...props} />; }
export function Select(props: SelectHTMLAttributes<HTMLSelectElement>) { return <select className="v-input" {...props} />; }
export function Checkbox({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: ReactNode }) { const id = useId(); return <label className="v-check" htmlFor={id}><input id={id} type="checkbox" {...props} />{label}</label>; }
export function Radio({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: ReactNode }) { const id = useId(); return <label className="v-check" htmlFor={id}><input id={id} type="radio" {...props} />{label}</label>; }
export function Switch({ label, ...props }: InputHTMLAttributes<HTMLInputElement> & { label: ReactNode }) { const id = useId(); return <label className="v-switch" htmlFor={id}><input id={id} type="checkbox" role="switch" {...props} /><span aria-hidden="true" />{label}</label>; }

export function Tabs({ tabs, defaultTab, label }: { tabs: { id: string; label: string; panel: ReactNode; disabled?: boolean }[]; defaultTab?: string; label: string }) { const [active, setActive] = useState(defaultTab ?? tabs[0]?.id); const chosen = tabs.find((tab) => tab.id === active) ?? tabs[0]; return <div><div className="v-tabs" role="tablist" aria-label={label}>{tabs.map((tab) => <button key={tab.id} role="tab" id={`tab-${tab.id}`} aria-selected={chosen.id === tab.id} aria-controls={`panel-${tab.id}`} disabled={tab.disabled} onClick={() => setActive(tab.id)}>{tab.label}</button>)}</div><div role="tabpanel" id={`panel-${chosen.id}`} aria-labelledby={`tab-${chosen.id}`} className="v-tabs__panel">{chosen.panel}</div></div>; }
export function Disclosure({ summary, children, defaultOpen = false }: { summary: ReactNode; children: ReactNode; defaultOpen?: boolean }) { return <details className="v-disclosure" open={defaultOpen}><summary>{summary}</summary><div>{children}</div></details>; }
export function Alert({ tone = 'info', title, children }: { tone?: 'info' | 'success' | 'warning' | 'danger'; title: string; children?: ReactNode }) { return <div className={`v-alert v-alert--${tone}`} role={tone === 'danger' ? 'alert' : 'status'}><strong>{title}</strong>{children && <div>{children}</div>}</div>; }
export function StatusTag({ tone = 'neutral', children }: { tone?: 'neutral' | 'success' | 'warning' | 'danger'; children: ReactNode }) { return <span className={`v-tag v-tag--${tone}`}>{children}</span>; }
export function LoadingIndicator({ label = 'Loading' }: { label?: string }) { return <span className="v-loading" role="status"><span aria-hidden="true" />{label}</span>; }

export function Dialog({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { const dialog = useRef<HTMLDialogElement>(null); useEffect(() => { const element = dialog.current; if (!element) return; if (open && !element.open) { if (typeof element.showModal === 'function') element.showModal(); else element.setAttribute('open', ''); } if (!open && element.open) { if (typeof element.close === 'function') element.close(); else element.removeAttribute('open'); } }, [open]); return <dialog ref={dialog} className="v-dialog" aria-labelledby="v-dialog-title" onCancel={(event) => { event.preventDefault(); onClose(); }} onClick={(event) => { if (event.target === dialog.current) onClose(); }}><div><h2 id="v-dialog-title">{title}</h2>{children}</div></dialog>; }

export function DataTable({ caption, columns, rows }: { caption: string; columns: { key: string; label: string }[]; rows: Record<string, ReactNode>[] }) { return <div className="v-table-wrap"><table className="v-table"><caption>{caption}</caption><thead><tr>{columns.map((column) => <th key={column.key} scope="col">{column.label}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{columns.map((column) => <td key={column.key}>{row[column.key]}</td>)}</tr>)}</tbody></table></div>; }
